name: Backup Git repository

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  BackupGit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: orbit
      uses: linuxsuren/orbit-assistant@master
      env:
        ORBIT_TOKEN: ${{ secrets.ORBIT_TOKEN }}
